#!/bin/bash -e
# Regen SimpleInvoices MySQL user random password

. /etc/default/inithooks

PASSWORD=$(mcookie)
CONF_FILE=/var/www/simpleinvoices/config/config.ini
VALUE="database.params.password 			= "

cp $CONF_FILE $CONF_FILE.backup
REPLACE=s/${VALUE}.*/${VALUE}${PASSWORD}/
sed -i "$REPLACE" "$CONF_FILE"

$INITHOOKS_PATH/bin/mysqlconf.py --user=simpleinv_usr --pass="$PASSWORD"